CREATE TABLE hostkey(
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	id_server varchar(10) NOT NULL,
	name varchar(30) NOT NULL,
	cpu_name varchar(100) NOT NULL,
	cpu_count INTEGER NOT NULL,
	cores INTEGER NOT NULL,
	frequency FLOAT NOT NULL,
	ram INTEGER NOT NULL,
	hdd_size INTEGER NOT NULL,
	ssd_size INTEGER NOT NULL,
	nvme_size INTEGER NOT NULL,
	datacenter varchar(30) NOT NULL,
	price FLOAT NOT NULL,
	limit_order INTEGER NOT NULL,
	date DATE NOT NULL
	);
	
CREATE TABLE reg_ru(
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	id_server varchar(10) NOT NULL,
	cpu_name varchar(100) NOT NULL,
	cpu_count INTEGER NOT NULL,
	cores INTEGER NOT NULL,
	frequency FLOAT NOT NULL,
	ram INTEGER NOT NULL,
	ddr3 INTEGER NOT NULL,
	ddr4 INTEGER NOT NULL,
	hdd_size INTEGER NOT NULL,
	ssd_size INTEGER NOT NULL,
	nvme_size INTEGER NOT NULL,
	datacenter varchar(30) NOT NULL,
	price FLOAT NOT NULL,
	date DATE NOT NULL
	);	
	
CREATE TABLE timeweb(
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	id_server varchar(10) NOT NULL,
	cpu_name varchar(100) NOT NULL,
	cpu_count INTEGER NOT NULL,
	cores INTEGER NOT NULL,
	frequency FLOAT NOT NULL,
	ram INTEGER NOT NULL,
	ddr3 INTEGER NOT NULL,
	ddr4 INTEGER NOT NULL,
	hdd_size INTEGER NOT NULL,
	ssd_size INTEGER NOT NULL,
	nvme_size INTEGER NOT NULL,
	gpu INTEGER NOT NULL,
	price FLOAT NOT NULL,
	date DATE NOT NULL
	);
	
CREATE TABLE servers_ru(
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	id_server varchar(10) NOT NULL,
	cpu_name varchar(100) NOT NULL,
	cpu_count INTEGER NOT NULL,
	gpu_count INTEGER,
	cores INTEGER NOT NULL,
	frequency FLOAT NOT NULL,
	ram INTEGER NOT NULL,
	ddr3 INTEGER NOT NULL,
	ddr4 INTEGER NOT NULL,
	hdd_size INTEGER NOT NULL,
	ssd_size INTEGER NOT NULL,
	nvme_size INTEGER NOT NULL,
	datacenter varchar(30) NOT NULL,
	price FLOAT NOT NULL,
	date DATE NOT NULL
	);
