CREATE TABLE configurations(
	id_config UUID PRIMARY KEY NOT NULL,
	cpu_name varchar(100) NOT NULL,
	cpu_count INTEGER NOT NULL,
	gpu varchar(30),
	gpu_count INTEGER,
	cores INTEGER NOT NULL,
	frequency FLOAT NOT NULL,
	ram INTEGER NOT NULL,
	ddr3 INTEGER,
	ddr4 INTEGER,
	hdd_size INTEGER NOT NULL,
	ssd_size INTEGER NOT NULL,
	nvme_size INTEGER NOT NULL,
	datacenter varchar(30),
	provider varchar(30) NOT NULL
	);

CREATE TABLE price(
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	id_config UUID NOT NULL,
	price FLOAT NOT NULL,
	date DATE NOT NULL
	);